modLoader = "kotlinforforge"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/LasmGratel/BetterP2P/issues"
license = "GPL-3.0"

[[mods]]
modId = "betterp2p"
version = "${version}"
displayName = "Better P2P"
authors = "Lasm Gratel, dyedquartz, AE2UEL Team, GlodBlock"
description = '''
An advanced tool for AE2, to manage P2P networks.
'''
#logoFile = ""

[[dependencies.betterp2p]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterp2p]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterp2p]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.betterp2p]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.betterp2p]]
modId = "ae2"
mandatory = true
versionRange = "[14.0.0,)"
ordering = "AFTER"
side = "BOTH"
