import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'net.neoforged.gradle.userdev' version '7.0.192'
    id 'org.jetbrains.kotlin.jvm' version "2.2.20"
    id 'com.diffplug.spotless-changelog' version "3.0.2"
    id 'com.diffplug.spotless' version '6.21.0'
    id 'com.palantir.git-version' version '3.0.0'
}

group = 'dev.lasm.betterp2p'
version = '1.5.0'

base.archivesName = project.name

java {
    withSourcesJar()
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

compileKotlin.compilerOptions.jvmTarget = JvmTarget.JVM_21

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'

        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.name
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.name
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.name
    }

    data {
        arguments.addAll '--mod', project.name, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

repositories {
    maven { url = "https://maven.parchmentmc.org" } // Parchment mappings
    // architectury
    maven { url = 'https://maven.architectury.dev/' }
    // KFF
    maven {
        name "Kotlin for Forge"
        url "https://thedarkcolour.github.io/KotlinForForge/"
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    implementation "org.appliedenergistics:appliedenergistics2:${ae2_version}"
    compileOnly 'org.jetbrains.kotlin:kotlin-stdlib'
    implementation 'thedarkcolour:kotlinforforge-neoforge:5.10.0'
}

spotless {
    encoding 'UTF-8'

    format 'misc', {
        target '.gitignore'

        trimTrailingWhitespace()
        indentWithSpaces(4)
        endWithNewline()
    }
    java {
        target 'src/main/java/**/*.java', 'src/test/java/**/*.java' // exclude api as they are not our files
        def orderFile = rootProject.file('spotless/spotless.importorder')
        def formatFile = rootProject.file('spotless/spotless.eclipseformat.xml')

        toggleOffOn()
        importOrderFile(orderFile)
        removeUnusedImports()
        endWithNewline()
        indentWithTabs(2)
        indentWithSpaces(4)
        //noinspection GroovyAssignabilityCheck
        eclipse('4.19').configFile(formatFile)
    }
    kotlin {
        target 'src/*/kotlin/**/*.kt'
        toggleOffOn()
        ktfmt('0.39').kotlinlangStyle()
        trimTrailingWhitespace()
        endWithNewline()
    }
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
        minecraft_version      : minecraft_version,
        minecraft_version_range: minecraft_version_range,
        neo_version            : neo_version,
        neo_version_range      : neo_version_range,
        loader_version_range   : loader_version_range,
        mod_id                 : project.name,
        mod_name               : mod_name,
        mod_license            : mod_license,
        mod_version            : project.version,
        mod_authors            : mod_authors,
        mod_description        : mod_description,
        ae2_version            : ae2_version
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

spotlessChangelog {
    changelogFile 'CHANGELOG.md'
    enforceCheck true
}
