org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.20.1
enabled_platforms=fabric,forge

archives_base_name=betterp2p
mod_version=1.4.0
maven_group=dev.lasm.betterp2p

architectury_version=9.1.12

fabric_loader_version=0.14.23
fabric_api_version=0.90.4+1.20.1

forge_version=1.20.1-47.2.1
# https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge/files
kotlin_for_forge_version=4.10.0

# https://modrinth.com/mod/ae2/versions?g=1.20.1
ae2_version=15.1.0
ae2_fabric_version=kywcQ25B

# https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin
fabric_kotlin_version=1.10.19+kotlin.1.9.23
