package dev.lasm.betterp2p.network.data

import appeng.parts.p2p.P2PTunnelPart
import net.minecraft.core.BlockPos
import net.minecraft.core.Direction
import net.minecraft.core.registries.Registries
import net.minecraft.nbt.CompoundTag
import net.minecraft.network.FriendlyByteBuf
import net.minecraft.resources.ResourceKey
import net.minecraft.resources.ResourceLocation
import net.minecraft.world.level.Level

data class P2PLocation(var pos: BlockPos, var facing: Direction, var dim: ResourceKey<Level>) {
    override fun hashCode(): Int {
        return hashP2P(pos, facing.ordinal, dim).hashCode()
    }

    /** Autogenerated equals by IntelliJ */
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as P2PLocation

        if (pos != other.pos) return false
        if (dim != other.dim) return false
        if (facing != other.facing) return false

        return true
    }
}

fun writeP2PLocation(buf: FriendlyByteBuf, loc: P2PLocation) {
    buf.writeLong(loc.pos.asLong())
    buf.writeByte(loc.facing.ordinal)
    buf.writeResourceKey(loc.dim)
}

fun readP2PLocation(buf: FriendlyByteBuf): P2PLocation? {
    return try {
        P2PLocation(
            pos = BlockPos.of(buf.readLong()),
            facing = Direction.values()[buf.readByte().toInt()],
            dim = buf.readResourceKey(Registries.DIMENSION)
        )
    } catch (e: Exception) {
        e.printStackTrace()
        null
    }
}

fun writeP2PLocation(loc: P2PLocation?): CompoundTag {
    val nbt = CompoundTag()

    if (loc != null) {
        nbt.putLong("pos", loc.pos.asLong())
        nbt.putByte("facing", loc.facing.ordinal.toByte())
        nbt.putString("dim", loc.dim.location().toString())
    }

    return nbt
}

fun readP2PLocation(tag: CompoundTag): P2PLocation? {
    return try {
        P2PLocation(
            pos = BlockPos.of(tag.getLong("pos")),
            facing = Direction.values()[tag.getByte("facing").toInt()],
            dim = ResourceKey.create(Registries.DIMENSION, ResourceLocation.parse(tag.getString("dim")))
        )
    } catch (e: Exception) {
        e.printStackTrace()
        null
    }
}

fun P2PTunnelPart<*>.toLoc() = P2PLocation(blockEntity.blockPos, side, level.dimension())
