package dev.lasm.betterp2p.network.data

import appeng.parts.p2p.P2PTunnelPart
import com.mojang.serialization.Codec
import com.mojang.serialization.codecs.RecordCodecBuilder
import io.netty.buffer.ByteBuf
import net.minecraft.core.BlockPos
import net.minecraft.core.Direction
import net.minecraft.core.registries.Registries
import net.minecraft.network.codec.StreamCodec
import net.minecraft.resources.ResourceKey
import net.minecraft.world.level.Level

data class P2PLocation(val pos: BlockPos, val facing: Direction, val dim: ResourceKey<Level>) {

    companion object {
        val CODEC: Codec<P2PLocation> =
            RecordCodecBuilder.create { instance ->
                instance
                    .group(
                        BlockPos.CODEC.fieldOf("pos").forGetter(P2PLocation::pos),
                        Direction.CODEC.fieldOf("facing").forGetter(P2PLocation::facing),
                        ResourceKey.codec(Registries.DIMENSION)
                            .fieldOf("dim")
                            .forGetter(P2PLocation::dim)
                    )
                    .apply(instance, ::P2PLocation)
            }
        val STREAM_CODEC: StreamCodec<ByteBuf, P2PLocation> =
            StreamCodec.composite(
                BlockPos.STREAM_CODEC,
                P2PLocation::pos,
                Direction.STREAM_CODEC,
                P2PLocation::facing,
                ResourceKey.streamCodec(Registries.DIMENSION),
                P2PLocation::dim,
                ::P2PLocation
            )
    }

    override fun hashCode(): Int {
        return hashP2P(pos, facing.ordinal, dim).hashCode()
    }

    /** Autogenerated equals by IntelliJ */
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as P2PLocation

        if (pos != other.pos) return false
        if (dim != other.dim) return false
        if (facing != other.facing) return false

        return true
    }
}

fun P2PTunnelPart<*>.toLoc() = P2PLocation(blockEntity.blockPos, side, level.dimension())
