modLoader = "kotlinforforge"
loaderVersion = "[5,)"
issueTrackerURL = "https://github.com/LasmGratel/BetterP2P/issues"
license = "GPL-3.0"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = "${mod_description}"
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ae2"
mandatory = true
versionRange = "[${ae2_version},)"
ordering = "AFTER"
side = "BOTH"
